[package]
name = "rw"
version = "0.13.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "rw"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", default-features = false, features = ["form", "json", "query", "rustls"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
base64 = "0.23"
dirs = "6"
write_atomic = "0.7"
webbrowser = "1"
uuid = { version = "1", features = ["v4"] }
rpassword = "7"
json_dotpath = "1"
self_update = { version = "1.0.0-rc.6", default-features = false, features = ["reqwest", "rustls", "github", "archive-tar", "compression-tar-gz"] }
validator = { version = "0.21", features = ["derive"] }
regex = "1"
tabled = "0.21.0"

[dev-dependencies]
assert_cmd = "2"
mockito = "1"
predicates = "3"
tempfile = "3"
